version: "3.8"

services:
  configurator_tremor:
    image: tremorproject/tremor:edge
    depends_on:
      - quota_service_1
      - quota_service_2
    container_name: configurator_tremor
    environment:
      - RUST_BACKTRACE=full
      - TREMOR_PATH=/opt/local/tremor/lib:/etc/tremor/lib
    volumes:
      - ./etc/tremor:/etc/tremor:rw
      - ./var/log:/var/log:rw
    ports:
      - 9898:9898 # tremor api
      - 9139:9139 # the configurator
    networks:
      - net

  quota_service_1:
    image: tremorproject/tremor:edge
    container_name: quota_service_1
    environment:
      - RUST_BACKTRACE=full
    volumes:
      - ../36_quota_service/etc/tremor:/etc/tremor
    ports:
      - 8139:8139
    networks:
      - net
    depends_on:
      elasticsearch:
        condition: service_healthy


  quota_service_2:
    image: tremorproject/tremor:edge
    container_name: quota_service_2
    environment:
      - RUST_BACKTRACE=full
    volumes:
      - ../36_quota_service/etc/tremor:/etc/tremor
    ports:
      - 8140:8139
    networks:
      - net
    depends_on:
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    environment:
    - bootstrap.memory_lock=true
    - cluster.name=docker-cluster
    - cluster.routing.allocation.disk.threshold_enabled=false
    - discovery.type=single-node
    - ES_JAVA_OPTS=-XX:UseAVX=2 -Xms1g -Xmx1g
    ulimits:
      memlock:
        hard: -1
        soft: -1
    volumes:
    - esdata:/usr/share/elasticsearch/data
    ports:
    - 9200:9200
    networks:
    - net
    healthcheck:
      interval: 20s
      retries: 10
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    networks:
    - net

networks:
  net:
    driver: bridge

volumes:
  esdata:
    driver: local