version: "3.7"

services:
  tremor-server:
    image: tremorproject/tremor:0.11
    ports:
      - 9898:9898
      - 8139:8139
    environment:
      - RUST_BACKTRACE=full
    volumes:
      - ../30_servers_lt_http/etc/tremor:/etc/tremor:rw
      - ../30_servers_lt_http/var/log:/var/log:rw
  tremor-proxy:
    image: tremorproject/tremor:0.11
    depends_on:
      - tremor-server
    ports:
      - 9899:9898
      - 9139:9139
    environment:
      - RUST_BACKTRACE=full
    volumes:
      - ./etc/tremor:/etc/tremor:rw
      - ./var/log:/var/log:rw
